### ISSUE TITLE
Support for Asset Bundle manifest in Build and Run

### ISSUE THREAD

**Issue by nopol10** [google/play-instant-unity-plugin#11]
Hi, I think it would be helpful for users to be able to specify the `assetBundleManifestPath` in BuildPlayerOptions for the Build And Run function if they use asset bundles for their Instant App (to prevent stuff used in asset bundles from getting stripped).

Cheers

**Comment by thanwah** [comment]
This is a great suggestion, thanks!

I'm still thinking through where to put the UI for specifying the `assetBundleManifestPath`, but I should be able to get this added to the plugin.
