### ISSUE TITLE
Unity 2018.3 - link.xml doesn't work when build for console

### ISSUE THREAD

**Issue by appxplore-tech** [google/play-instant-unity-plugin#134]
Hi

Recently I had set the Strip Engine Code to true and also Managed Stripping Level to Medium in Unity3d 2018.3. I manage to build an APK that is playable from my phone but when i try to build an ZIP file from the Build for console and test from my phone through the "TRY NOW" button, It doesn't work as it tells me the class has been stripped down.

Is there any way for me to strip the engine code with the link.xml?

THank you.

**Comment by jamcohen** [comment]
Hello, thanks for reaching out.

I have a couple questions to help me understand the issue:
1.  When you build the APK, are building/running it using the menu option: PlayInstant -> Build & Run?
2. When you build the APK, do you have a link.xml file in your Asset folder?
3. Which class fails to load?
4. Is that class referenced in your scene, or is it attached to a prefab in an AssetBundle?
5. If you are using AssetBundles, what is the "AssetBundle Manifest" field in the "Play Instant Build Settings" set to?

Any logs that you can send would also be very helpful.

Thanks!
