### ISSUE TITLE
how to make the game size reduce to 10MB limit

### ISSUE THREAD

**Issue by manlok1992** [google/play-instant-unity-plugin#136]
My game has many resources. I remove many unused resource in the project. I built the game in `PlayInstant-> Build for Play Console`. I built a 135MB zip file. I create a new project only import the google instant apps plugin and build it. I built a 15.1MB zip file.
So I don't know how to make the game size reduce to 10MB limit

**Comment by thanwah** [comment]
There are a number of strategies for reducing APK size, for example moving some of your assets to an AssetBundle and fetching them from a CDN. The plugin's "Quick Deploy" feature can help with this.

If I'm understanding correctly, you've created a blank project and the APK was still 15MB. To reduce this you should look at changing some of the project settings. For example, try enabling both IL2CPP and engine stripping.

We are actively working on some new features to make it easier to fit within the size limit. In the meantime you might consider joining the beta program:
https://docs.google.com/forms/d/1rRPO4V8b0udKVwJknq8ZkUOnE-oKbHochLE-ry_rvtA/edit

**Comment by manlok1992** [comment]
Hello, I enabled the  IL2CPP and engine stripping in Player Setting. I also create asset bundle for the game. But the size currently is 4xMB.

**Comment by manlok1992** [comment]
Our game has many object is created in runtime. So some object, texture material cannot build into the asset bundle using Quick Deploy feature.

**Comment by jamcohen** [comment]
I have a couple questions to help me understand the issue:
1. What version of Unity are you using?
2. If you build a blank project with IL2CPP and engine stripping enabled, how big is the resulting apk?

If you can get an initial loading screen under 10MB, then you can use Unity's AssetBundle Browser to package the rest of your assets into an asset bundle. Then you can load that asset bundle from a CDN.

**Comment by manlok1992** [comment]
1. I am using Unity 2018.3.11f1
2. I still remember I built the blank project with IL2CPP is about 15MB.

I have used the asset bundle for almost resources.

**Comment by jamcohen** [comment]
What target architectures do you have enabled?
If you select just one target architecture you should get a 7.5MB apk.

**Comment by manlok1992** [comment]
oh... I don't know I can select one target architecture.
