### ISSUE TITLE
Invalid value for the 'android:targetSandboxVersion' attribute in the AndroidManifest.

### ISSUE THREAD

**Issue by TonAbs** [google/play-instant-unity-plugin#145]
I cant upload my apk to the google developer console because of the above error. I have checked the `AndroidManifest` file generated by the plugin at `Temp\gradleOut\unityLibrary\src\main ` and it indeed has `android:targetSandboxVersion = "2"`. However, when I inspect the apk in android studio, the final manifest no longer has this property and I am guessing this is why I am getting the error. Is there a solution to this? I am using Unity 2019.3

Thanks

**Comment by thanwah** [comment]
This issue should be fixed as of https://github.com/google/play-instant-unity-plugin/commit/f73453a40295aca5f8bb042c7baf33054a9d6ba2. I will create a new 0.11 release that contains this commit.

**Comment by thanwah** [comment]
Created a new release: https://github.com/google/play-instant-unity-plugin/releases/tag/v0.11

Please let me know if you have any issues with this release. Thanks!

**Comment by TonAbs** [comment]
Thanks alot! this worked! There was a `Attribute meta-data#play-instant-unity-plugin.version@value value=(0.11) from AndroidManifest.xml:6:65-85 is also present at [:unityLibrary] AndroidManifest.xml:82:13-33 value=(0.10).` error stopping it from  building after the upgrade, but I fixed this by just simply changing the plugin version in `Assets/Plugins/Android/AndroidManifest.xml` from 0.10 to 0.11
