### ISSUE TITLE
Zip creation errors when path has spaces in it

### ISSUE THREAD

**Issue by frenb** [google/play-instant-unity-plugin#19]
Zip creation failed: Failed to run '/Library/Java/JavaVirtualMachines/default/Contents/Home/bin/jar cvf /Users/bfrenkel/Documents/InstantGames/Google Play Instant Sample/SphereBlastPCV1.zip -C /var/folders/js/zwj26yx53j1bw9ywks160ryr00772k/T/ base.apk'
stdout:
added manifest
adding: base.apk(in = 16531357) (out= 15605940)(deflated 5%)

stderr:
Play : no such file or directory
Instant : no such file or directory
Sample/SphereBlastPCV1.zip : no such file or directory

exit code: 1

**Comment by thanwah** [comment]
Thanks for the bug report. I'll prepare a fix.

**Comment by frenb** [comment]
NP! FYI, I've confirmed that removing the spaces from directory resolved the issue.
