### ISSUE TITLE
Infinite spinning when deployed to device

### ISSUE THREAD

**Issue by jbattersby-bb** [google/play-instant-unity-plugin#29]
Hi,

When I deploy the Instant App via **Build and Run** it deploys but I'm left with a spinning circle that doesn't seem to end. I'm not seeing anything particularly obvious in the logcat - do you have any suggestions?
![device-2018-08-15-182501](https://user-images.githubusercontent.com/18311185/44162533-963ff280-a0b8-11e8-890c-34d307666df8.png)

**Comment by thanwah** [comment]
Thank you for reporting this. I hadn't seen this issue on an Android 8 or 9 device, but I was just now able to reproduce your issue via Build and Run from Unity 2017.4 to a Nexus 6 running Android 7.1.1.

I will investigate further when I'm in the office tomorrow and able to debug in more depth.

If you have another device to use for testing, that could hopefully unblock you until I can resolve this issue.

**Comment by jbattersby-bb** [comment]
Ah.. yeah.. I could have probably helped with supplying that information because that's exactly what I'm using!

Sadly no other devices to play with until Friday but I've other things to get on with. If there's anything I can help with let me know!

**Comment by thanwah** [comment]
The fixed release of "Google Play services for Instant Apps" version 3.12 is fully rolled out, so this issue shouldn't occur anymore. Please reopen this bug if you still see the same issue, and report the version of "Google Play services for Instant Apps". Thanks.
