### ISSUE TITLE
Is AndroidManifest necessary and "ShowInstallPrompt"  can only  work after upload to google play?

### ISSUE THREAD

**Issue by Zhuwenjie-stan** [google/play-instant-unity-plugin#69]
Hi, I'm trying  to convert my existing Unity game into an Instant Game , and I Create an empty project by u3d 2018.2.5 , and create a loading scene to download assetbundle that contains my app's core game-play,
And I found that while I Change Android Build Type By 【PlayInstant/BuildSetting】and leave all blank default  then  Click Save, the Unity Console show the info "Saving Play Instant build settings..." and  had a warning message say "Assets/GooglePlayInstant/InstallLauncher.cs(82,13): warning CS0162: Unreachable code detected " , and  it did not  say message  like  "Successfully updated Assets/Plugins/Android/AndroidManifest.xml" ,And I wanna know Is the file AndroidManifest necessary In folder Plugins/Android ？ If its yes , What are the minimum requirements for file content?
Another thing confuse me is when I build The zip to upload to GooglePlay , I get apk and a mete-inf , 
and I install the apk in my device  and click a button that call the method "InstallLauncher.ShowInstallPrompt();" but nothing happened , its meats that this method can only work after upload to GooglePlay？
I'll appreciate it very much if you could help me！

**Comment by thanwah** [comment]
Hi, thanks for your questions.

For versions of Unity before 2018 it was necessary for the plugin to create a Assets/Plugins/Android/AndroidManifest.xml file. Starting with 2018.1 though, we're able to use a better approach where we update the AndroidManifest.xml later in the build process. Currently, there is no "settings saved" message, and the warnings are distracting. I will do a PR to clean up the warnings you see and add a message when saving settings on Unity 2018+.

For InstallLauncher.ShowInstallPrompt() what happens is that the instant app shows a Play Store dialog to install the full game. If this is a new game that hasn't been published, then the Play Store won't know about it. If this is an existing game, then the dialog should display the title/details of the game and offer an install button. If the _installable_ game is published on the Play Store, the dialog should work even if the _instant_ game isn't published yet.

**Comment by thanwah** [comment]
Hi again, I submitted a change that fixes the logging and warning messages. I haven't created a new .unitypackage release, however, so you'd only see these fixes if you "git clone" the plugin into your project. Please reopen this issue if there is any followup discussion you'd like to have on the 2 issues you brought forward. Thanks!

**Comment by thanwah** [comment]
Thanks for the additional information. I'm not sure yet what could be causing this issue.

Do you mind sharing:
- The type of device you're using and version of Android? (Settings -> System -> About Phone)
- The version of Google Play Store? (Settings -> Apps)
- A screenshot (or video) of what you're seeing?

**Comment by Zhuwenjie-stan** [comment]
Thanks again.
1. My Google Play Store version is 11.7.11.
![screenshot_2018-09-22-20-21-49-099_com miui secur](https://user-images.githubusercontent.com/9164100/45917259-cfcd0000-bea5-11e8-9110-c9b218d8af99.png)

2. My device android version is 7.0
![screenshot_2018-09-22-20-21-12-703_com android se](https://user-images.githubusercontent.com/9164100/45917261-d491b400-bea5-11e8-88ca-380de81b5228.png)

And I guess that is not because of the device or Google Play Store, I use another phone like Samsung s9 with android 8.0, got the same result.BTW, I can see some app has the "Try Now" button in Google Play Store, like Candy Crash and Clash Royale.

I just import the plugin to a new empty project and change build type to instant, then change package name and version code, and do a signature. It's a simple scene with an install button call  method 
ShowInstallPrompt().I am sure the process has already entered this method. I could see log added by myself in the mobile phone.

I  thought it may be caused by the Google Play Store would resign the apk So the apk signature with being different after uploading to Google Play Store, But when I upload my instant app to Google Play Store and download it, the signature was changed indeed, but the  "ShowInstallPrompt()" still didn't work. (I had also tried the Read Cookie and Write Cookie method, the two methods can work. )

**Comment by thanwah** [comment]
Thanks for providing this information. That is a recent version of Google Play Store, so I'd expect that it should work.

If you look at the output from "adb logcat" do you see lines like either of the following?

```
I/ActivityManager: START u0 {act=com.google.android.finsky.action.IA_INSTALL dat=market://details?id=<package name> pkg=com.android.vending cmp=com.android.vending/com.google.android.finsky.instantappsquickinstall.InstantAppsInstallEntryActivity (has extras)}

I/ActivityManager: START u0 {cmp=com.android.vending/com.google.android.finsky.instantappsquickinstall.InstantAppsInstallDialogActivity (has extras)}
```

Something else you could check is to "Try Now" on another Instant App (like Clash Royale) and check that the Install button works in that case.

**Comment by Zhuwenjie-stan** [comment]
Thank you for reply.@thanwah
I could see the info "**com.google.android.finsky.externalreferrer.i.run(43): Dropped referrer for _MyPackageName_ because dropped_already_installed**"  and  "**com.google.android.finsky.instantappsquickinstall.InstantAppsInstallEntryActivity.onCreate(32): intent validation failed, exiting**" by adb logcat.It means that I had open the same URL while the install-type app is already installed? But I used the phone that  has not install the app in google play store, it was the same.

Below is my unity setting.

![image](https://user-images.githubusercontent.com/9164100/46078972-4fb9d980-c1c8-11e8-9a4b-e0683d8bd5d9.png)

And how I call the method : 
![image](https://user-images.githubusercontent.com/9164100/46079901-061ebe00-c1cb-11e8-8d46-ee7d1e778a3e.png)

![image](https://user-images.githubusercontent.com/9164100/46079911-0f0f8f80-c1cb-11e8-8975-048b52989edd.png)

**Comment by thanwah** [comment]
Thanks for sharing those two log statements.

Unfortunately the Play Store "intent validation failed" message can be caused by many reasons, so I can't be sure specifically what's causing it in your case.

I'm curious about the "dropped_already_installed" message though. Is your app already installed on the device? It shouldn't be possible to even run the app if this is the case, but I just want to confirm.

Please reach out to me over email at play-instant-unity-plugin-support@googlegroups.com - perhaps you can provide me with a test app that demonstrates the problem so I can debug it further.

**Comment by Zhuwenjie-stan** [comment]
I have already sent you an email.
If there is any suggestions,please contact me.
thanks again.

**Comment by thanwah** [comment]
Hmm. I haven't received it yet. I just sent myself another test email to play-instant-unity-plugin-support@googlegroups.com from an external email account and received it immediately. Does it seem like the email went through? (No delivery errors?)

**Comment by Zhuwenjie-stan** [comment]
The email delivery fails when I send with the apk file, I had to change the extension to .txt, and send successfully,
If you change the extension back to .apk cannot install, I had resent an email to you and I upload the apk to Network Disk so you can download it with the link and password I offer in the email.

**Comment by thanwah** [comment]
Thank you for sending the email. I received it, and I have just replied.

**Comment by thanwah** [comment]
Resolved offline. Thanks.
